### ISSUE TITLE
Panics When AssemblyLine Instance is Not Online

### ISSUE THREAD

**Issue by xorhex** [xorhex/mlget#13]
```
Querying all services
  [*] AssemblyLine: 
panic: send on closed channel
goroutine 35 [running]:
main.hashFileAndCheck({0xc0003dbac0, 0x40}, 0x0?)
	~/src/mlget/mlget.go:398 +0x20a
main.downloadMalwareFromCLI.func2()
	~/src/mlget/mlget.go:244 +0x55
created by main.downloadMalwareFromCLI in goroutine 1
	~/src/mlget/mlget.go:242 +0xbe9
```

**Comment by xorhex** [comment]
Fixed, will be in the next release.
